/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GradeService } from "../grade.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GradeCreateInput } from "./GradeCreateInput";
import { GradeWhereInput } from "./GradeWhereInput";
import { GradeWhereUniqueInput } from "./GradeWhereUniqueInput";
import { GradeFindManyArgs } from "./GradeFindManyArgs";
import { GradeUpdateInput } from "./GradeUpdateInput";
import { Grade } from "./Grade";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GradeControllerBase {
  constructor(
    protected readonly service: GradeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Grade })
  @nestAccessControl.UseRoles({
    resource: "Grade",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: GradeCreateInput): Promise<Grade> {
    return await this.service.create({
      data: {
        ...data,

        assignmentId: data.assignmentId
          ? {
              connect: data.assignmentId,
            }
          : undefined,

        studentId: data.studentId
          ? {
              connect: data.studentId,
            }
          : undefined,
      },
      select: {
        assignmentId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        score: true,

        studentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Grade] })
  @ApiNestedQuery(GradeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Grade",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Grade[]> {
    const args = plainToClass(GradeFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        assignmentId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        score: true,

        studentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Grade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Grade",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: GradeWhereUniqueInput
  ): Promise<Grade | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        assignmentId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        score: true,

        studentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Grade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Grade",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: GradeWhereUniqueInput,
    @common.Body() data: GradeUpdateInput
  ): Promise<Grade | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          assignmentId: data.assignmentId
            ? {
                connect: data.assignmentId,
              }
            : undefined,

          studentId: data.studentId
            ? {
                connect: data.studentId,
              }
            : undefined,
        },
        select: {
          assignmentId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          score: true,

          studentId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Grade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Grade",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: GradeWhereUniqueInput
  ): Promise<Grade | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          assignmentId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          score: true,

          studentId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
