/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GradedItemService } from "../gradedItem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GradedItemCreateInput } from "./GradedItemCreateInput";
import { GradedItemWhereInput } from "./GradedItemWhereInput";
import { GradedItemWhereUniqueInput } from "./GradedItemWhereUniqueInput";
import { GradedItemFindManyArgs } from "./GradedItemFindManyArgs";
import { GradedItemUpdateInput } from "./GradedItemUpdateInput";
import { GradedItem } from "./GradedItem";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GradedItemControllerBase {
  constructor(
    protected readonly service: GradedItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GradedItem })
  @nestAccessControl.UseRoles({
    resource: "GradedItem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: GradedItemCreateInput
  ): Promise<GradedItem> {
    return await this.service.create({
      data: {
        ...data,

        grades: data.grades
          ? {
              connect: data.grades,
            }
          : undefined,
      },
      select: {
        activityType: true,
        createdAt: true,
        deadline: true,

        grades: {
          select: {
            id: true,
          },
        },

        id: true,
        maximum: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GradedItem] })
  @ApiNestedQuery(GradedItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GradedItem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<GradedItem[]> {
    const args = plainToClass(GradedItemFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        activityType: true,
        createdAt: true,
        deadline: true,

        grades: {
          select: {
            id: true,
          },
        },

        id: true,
        maximum: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GradedItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GradedItem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: GradedItemWhereUniqueInput
  ): Promise<GradedItem | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        activityType: true,
        createdAt: true,
        deadline: true,

        grades: {
          select: {
            id: true,
          },
        },

        id: true,
        maximum: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GradedItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GradedItem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: GradedItemWhereUniqueInput,
    @common.Body() data: GradedItemUpdateInput
  ): Promise<GradedItem | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          grades: data.grades
            ? {
                connect: data.grades,
              }
            : undefined,
        },
        select: {
          activityType: true,
          createdAt: true,
          deadline: true,

          grades: {
            select: {
              id: true,
            },
          },

          id: true,
          maximum: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GradedItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GradedItem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: GradedItemWhereUniqueInput
  ): Promise<GradedItem | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          activityType: true,
          createdAt: true,
          deadline: true,

          grades: {
            select: {
              id: true,
            },
          },

          id: true,
          maximum: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
